SELECT
  TO_CHAR(gamedate, 'YYYY-MM-DD')                                         AS gamedate,
  week,
  concat(lpad(hhour :: TEXT, 2, '0'), ':', lpad(mminute :: TEXT, 2, '0')) AS kickofftime,
  team,
  tpposition                                                              AS position,
  oppo,
  result,
  stadium,
  temperature,
  windspeed,
  wcond,
  ffp                                                                     AS ffp,
  rushtd,
  rushy,
  reyd,
  receps,
  (rtar + carries + passattm)                                             AS actions,
  round((rushy / (carries + 0.000001)) :: NUMERIC, 2)                     AS yardspercarry,
  round((reyd / (receps + 0.000001)) :: NUMERIC, 2)                       AS yardspercomp,
  passtd                                                                  AS passtd,
  tottd                                                                   AS tottd,
  passyd                                                                  AS passyd,
  passattm                                                                AS passattm,
  passc                                                                   AS passc,
  round((passc / (passattm + 0.000001)) :: NUMERIC, 2) * 100              AS compper,
  intercepts                                                              AS intercepts,
  twentyp,
  fortyp,
  sacks,
  fum,
  fgatt,
  fgm,
  round((fgm / (fgatt + 0.000001)) :: NUMERIC, 2) * 100                   AS fgper,
  pattm,
  pamade,
  (f20 + f30 + f40 + f50p)                                                AS f20p,
  (f30 + f40 + f50p)                                                      AS f30p,
  (f40 + f50p)                                                            AS f40p,
  f50p,
  longfg,
  fgblocked,
  pablocked
FROM ${table^}
WHERE ${where^}
ORDER BY ${orderBy^} gamedate
${limit^}
